name: Duo Review

on:
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: duoduo-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  issues: write

env:
  DROID_PATH: /Users/notdp/.local/bin/droid
  PR_NUMBER: ${{ github.event.pull_request.number }}
  PR_BRANCH: ${{ github.head_ref }}
  BASE_BRANCH: ${{ github.base_ref }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check-branch:
    runs-on: [self-hosted, macos, arm64]
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - id: check
        run: |
          if [[ "${{ github.head_ref }}" == bot/* ]]; then
            echo "should_run=false" >> $GITHUB_OUTPUT
          else
            echo "should_run=true" >> $GITHUB_OUTPUT
          fi

  duoduo:
    needs: check-branch
    if: needs.check-branch.outputs.should_run == 'true'
    runs-on: [self-hosted, macos, arm64]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pull latest skills
        run: |
          cd ~/.dotfiles && git fetch origin && git reset --hard origin/main

      - name: Cleanup old comments
        run: |
          ~/.dotfiles/skills/duoduo/scripts/cleanup-comments.sh ${{ env.PR_NUMBER }} ${{ github.repository }}

      - name: Duo Review
        env:
          PR_NUMBER: ${{ env.PR_NUMBER }}
          PR_BRANCH: ${{ env.PR_BRANCH }}
          BASE_BRANCH: ${{ env.BASE_BRANCH }}
          REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $DROID_PATH exec -m claude-opus-4-5-20251101 -r high --auto high "
          <system-instruction>
          你是 Orchestrator，负责编排 duoduo review流程。
          首先 load skill: duoduo

          ## 关键变量
          S=~/.factory/skills/duoduo/scripts
          PR_NUMBER=$PR_NUMBER
          REPO=$REPO
          PR_BRANCH=$PR_BRANCH
          BASE_BRANCH=$BASE_BRANCH

          ## ⚠️ 严格禁止
          - 禁止读取 PR diff、代码文件、REVIEW.md
          - 禁止自己审查代码
          - 只能执行脚本、读取 Redis 状态、读取 PR 评论判断共识

          ## 执行流程
          1. 读取 stages/1-pr-review.md 获取阶段 1 详细指令
          2. 按指令执行：初始化 Redis → 创建占位评论 → 并行启动 Codex/Opus
          3. 等待完成后进入阶段 2，依次执行后续阶段
          4. 每个阶段执行前必须先读取对应的 stages/*.md 文件

          ## 开始
          立即执行阶段 1。
          </system-instruction>
          "
