#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sys
from pathlib import Path


try:
    from scripts.hooks.redact import assert_no_secrets
except ModuleNotFoundError:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    from hooks.redact import assert_no_secrets


ALLOWED_FRONTMATTER_FIELDS = {
    "title",
    "date",
    "problem_type",
    "type",
    "created",
    "last_accessed",
    "status",
    "valid_from",
    "valid_to",
    "stale_reason",
    "superseded_by",
    "trust",
    "keywords",
    "tags",
    "related",
    "origin_session",
    "origin_project",
    "scope",
    "verify",
    "applies_to",
}
REQUIRED_FRONTMATTER_FIELDS = {"title", "date", "problem_type"}
INDEX_HEADER = "# Memory Index\n\n> Generated by `scripts/build_memory_index.py`; do not edit by hand.\n\n"


class IndexErrorWithSource(ValueError):
    pass


def parse_frontmatter(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise IndexErrorWithSource(f"{path}: missing frontmatter")
    end = text.find("\n---", 4)
    if end == -1:
        raise IndexErrorWithSource(f"{path}: unterminated frontmatter")
    raw = text[4:end]
    assert_no_secrets(raw, source=str(path))
    data: dict[str, str] = {}
    for line in raw.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if ":" not in stripped:
            raise IndexErrorWithSource(f"{path}: invalid frontmatter line {line!r}")
        key, value = stripped.split(":", 1)
        key = key.strip()
        value = value.strip().strip('"\'')
        if key == "level":
            raise IndexErrorWithSource(f"{path}: frontmatter field 'level' is forbidden; location is authority")
        if key not in ALLOWED_FRONTMATTER_FIELDS:
            raise IndexErrorWithSource(f"{path}: unsupported frontmatter field {key!r}")
        data[key] = normalize_value(value)
    missing = sorted(REQUIRED_FRONTMATTER_FIELDS - data.keys())
    if missing:
        raise IndexErrorWithSource(f"{path}: missing required frontmatter field(s): {', '.join(missing)}")
    return data


def normalize_value(value: str) -> str:
    if value.startswith("[") and value.endswith("]"):
        items = [item.strip().strip('"\'') for item in value[1:-1].split(",") if item.strip()]
        return ", ".join(items)
    return value


def note_rows(user_dir: Path) -> list[tuple[Path, dict[str, str]]]:
    rows = []
    for path in sorted(user_dir.glob("*.md")):
        if path.name == "INDEX.md":
            continue
        rows.append((path, parse_frontmatter(path)))
    return rows


def table_cell(value: str) -> str:
    return value.replace("|", r"\|").replace("\n", " ")


def render_index(user_dir: Path) -> str:
    rows = note_rows(user_dir)
    lines = [INDEX_HEADER.rstrip(), "", "| File | Title | Problem Type | Status | Keywords | Origin |", "|---|---|---|---|---|---|"]
    for path, meta in rows:
        keywords = meta.get("keywords") or meta.get("tags") or ""
        lines.append(
            "| {file} | {title} | {problem_type} | {status} | {keywords} | {origin} |".format(
                file=table_cell(path.name),
                title=table_cell(meta.get("title", "")),
                problem_type=table_cell(meta.get("problem_type", "")),
                status=table_cell(meta.get("status", "active")),
                keywords=table_cell(keywords),
                origin=table_cell(meta.get("origin_session", "")),
            )
        )
    output = "\n".join(lines).rstrip() + "\n"
    assert_no_secrets(output, source=str(user_dir / "INDEX.md"))
    return output


def main() -> int:
    parser = argparse.ArgumentParser(description="Build or verify memory/user/INDEX.md from note frontmatter.")
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--verify", action="store_true")
    args = parser.parse_args()

    user_dir = args.root.resolve() / "memory" / "user"
    user_dir.mkdir(parents=True, exist_ok=True)
    index_path = user_dir / "INDEX.md"
    try:
        rendered = render_index(user_dir)
    except Exception as exc:
        sys.stderr.write(f"build_memory_index failed: {exc}\n")
        return 1

    if args.verify:
        current = index_path.read_text(encoding="utf-8") if index_path.exists() else ""
        if current != rendered:
            sys.stderr.write("build_memory_index verify failed: INDEX.md is missing or stale\n")
            return 1
        sys.stdout.write("build_memory_index verify passed\n")
        return 0

    index_path.write_text(rendered, encoding="utf-8")
    sys.stdout.write(f"wrote {index_path}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
